/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_B */
#define LED_B_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_0_INBUF_ENABLED 0u
#define LED_B_0_INIT_DRIVESTATE 0u
#define LED_B_0_INIT_MUXSEL 0u
#define LED_B_0_INPUT_SYNC 2u
#define LED_B_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_0_NUM 4u
#define LED_B_0_PORT GPIO_PRT12
#define LED_B_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_B_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_INBUF_ENABLED 0u
#define LED_B_INIT_DRIVESTATE 0u
#define LED_B_INIT_MUXSEL 0u
#define LED_B_INPUT_SYNC 2u
#define LED_B_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_NUM 4u
#define LED_B_PORT GPIO_PRT12
#define LED_B_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_R */
#define LED_R_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_0_INBUF_ENABLED 0u
#define LED_R_0_INIT_DRIVESTATE 0u
#define LED_R_0_INIT_MUXSEL 0u
#define LED_R_0_INPUT_SYNC 2u
#define LED_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_0_NUM 5u
#define LED_R_0_PORT GPIO_PRT12
#define LED_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_R_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_INBUF_ENABLED 0u
#define LED_R_INIT_DRIVESTATE 0u
#define LED_R_INIT_MUXSEL 0u
#define LED_R_INPUT_SYNC 2u
#define LED_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_NUM 5u
#define LED_R_PORT GPIO_PRT12
#define LED_R_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* V_LDR */
#define V_LDR_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define V_LDR_0_INBUF_ENABLED 0u
#define V_LDR_0_INIT_DRIVESTATE 1u
#define V_LDR_0_INIT_MUXSEL 0u
#define V_LDR_0_INPUT_SYNC 2u
#define V_LDR_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define V_LDR_0_NUM 4u
#define V_LDR_0_PORT GPIO_PRT0
#define V_LDR_0_SLEWRATE CY_GPIO_SLEW_FAST
#define V_LDR_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define V_LDR_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define V_LDR_INBUF_ENABLED 0u
#define V_LDR_INIT_DRIVESTATE 1u
#define V_LDR_INIT_MUXSEL 0u
#define V_LDR_INPUT_SYNC 2u
#define V_LDR_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define V_LDR_NUM 4u
#define V_LDR_PORT GPIO_PRT0
#define V_LDR_SLEWRATE CY_GPIO_SLEW_FAST
#define V_LDR_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ADC_Pin */
#define ADC_Pin_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define ADC_Pin_0_INBUF_ENABLED 0u
#define ADC_Pin_0_INIT_DRIVESTATE 1u
#define ADC_Pin_0_INIT_MUXSEL 0u
#define ADC_Pin_0_INPUT_SYNC 2u
#define ADC_Pin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ADC_Pin_0_NUM 3u
#define ADC_Pin_0_PORT GPIO_PRT10
#define ADC_Pin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ADC_Pin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ADC_Pin_DRIVEMODE CY_GPIO_DM_ANALOG
#define ADC_Pin_INBUF_ENABLED 0u
#define ADC_Pin_INIT_DRIVESTATE 1u
#define ADC_Pin_INIT_MUXSEL 0u
#define ADC_Pin_INPUT_SYNC 2u
#define ADC_Pin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ADC_Pin_NUM 3u
#define ADC_Pin_PORT GPIO_PRT10
#define ADC_Pin_SLEWRATE CY_GPIO_SLEW_FAST
#define ADC_Pin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
